weights: weights/yolov5s.pt
cfg: models/yolov5s.yaml
data: /media/yangxilab/60b7e6d0-7a2e-43a9-b5c8-164b0bf25f75/zzl/Code/yolov5_obb-master/data/ShipRSImageNet.yaml
hyp: data/hyps/obb/hyp.finetune_dota.yaml
epochs: 2
batch_size: 1
imgsz: 1024
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: debug
name: ShipRS
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: debug/ShipRS
